[package]
name = "gw-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
managed-process= { path = "../managed-process" }
axum = "0.8.8"
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
