[package]
name = "gw-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
managed-process = { path = "../managed-process" }
axum = { version = "0.8.8", features = ["http2", "macros", "multipart", "ws"] }
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
axum-reverse-proxy = { version = "1.1.0", features = ["full"] }
inference-backends = { path = "../inference-backends" }
serde = { version = "1.0.228", features = ["serde_derive"] }
rand = "0.9.2"
