[package]
name = "inference-backends"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
managed-process= { path = "../managed-process" }
serde = { version = "1.0.228" }
